### PR TITLE
added cmake flag SGNL_OPT_BUILD_TESTS

### PR DESCRIPTION
**Pull request by theShmoo**
Added flag to skip building the tests if this library is used by another via CMake

### CODE REVIEW

**Comment by thomastrapp** [comment]
Can you describe how `signal-wrangler` is included in your project? (or a link to your repository, if available)

The easiest way to depend on signal-wrangler in a cmake project is by installing it, for example:
```
mkdir -p build/ && cd build/
cmake ..
make
make install
```

And then in your own cmake project, add:
```
find_package(Sgnl REQUIRED)
target_link_libraries(my-project sgnl::sgnl ...)
```

Thank you for your interest in this project!

**Comment by theShmoo** [comment]
I include it with FETCH:

```

FetchContent_Declare(
  signal-wrangler
  GIT_REPOSITORY https://github.com/theShmoo/signal-wrangler
)

FetchContent_GetProperties(signal-wrangler)
if (NOT signal-wrangler_POPULATED)
  FetchContent_Populate(signal-wrangler)
  add_subdirectory(${signal-wrangler_SOURCE_DIR} ${signal-wrangler_BINARY_DIR} EXCLUDE_FROM_ALL)
  target_include_directories(sgnl SYSTEM INTERFACE $<BUILD_INTERFACE:${signal-wrangler_SOURCE_DIR}/include>)
endif ()
```

so that it is build with the project

**Comment by thomastrapp** [comment]
The root of the problem is fixed now: The tests are truly optional and the hard dependency on 'Catch2' is gone.

I added an example using FetchContent to the readme:

```CMAKE
cmake_minimum_required(VERSION 3.14 FATAL_ERROR)
project(my-example)

include(FetchContent)
FetchContent_Declare(
  signal-wrangler
  GIT_REPOSITORY https://github.com/thomastrapp/signal-wrangler
  GIT_TAG v0.4.0)
FetchContent_MakeAvailable(signal-wrangler)

add_executable(my-example "example/example.cpp")
target_link_libraries(my-example sgnl::sgnl)
```

Thank you for bringing this to my attention.

**Comment by theShmoo** [comment]
Great thank you very much!

Thanks for this library!

**Pull request closed without merging**
